version: "3"

services:
  backend:
    image: backend:1
    ports:
      - 8080:8080
    environment:
      PG_NAME: postgres
      PG_USER: admin
      PG_PASSWORD: admin
      PG_HOST: db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "admin" ]
    ports:
      - 5432:5432

  migrate:
    image: migrate:1
    environment:
      PGDATABASE: postgres
      PGUSER: admin
      PGPASSWORD: admin
      PGHOST: db
      PGPORT: 5432
    depends_on:
      db:
        condition: service_healthy
